# Generated by Django 5.1.4 on 2024-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pf_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="hello",
            field=models.TextField(blank=True),
        ),
    ]
