# Generated by Django 5.1.4 on 2024-12-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pf_tracker", "0003_remove_company_hello"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="hello",
            field=models.TextField(blank=True),
        ),
    ]
