# Generated by Django 5.1.4 on 2024-12-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pf_tracker", "0005_remove_company_hello"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pf_account_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
